port: "4000"
cache_size: 10

nats:
  url: "nats://localhost:4222"
  clusterid: "test-cluster"
  clientid: "order-consumer"

db:
  host: "localhost"
  port: "5432"
  dbname: "orderswb"
  user: "postgres"
  sslmode: "disable"